version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - nextjs-app
    networks:
      - quickesta-network
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/quickesta.com.pem:/etc/nginx/quickesta.com.pem
      - ./nginx/quickesta.com.key:/etc/nginx/quickesta.com.key

  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '3004'
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env:ro
    networks:
      - quickesta-network
    restart: always

networks:
  quickesta-network:
    name: quickesta-network
    driver: bridge
